from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from typing import List, Union, Optional
from api.auth import verify_api_key

router = APIRouter()


class RichScoreRequest(BaseModel):
    """Rich transaction schema — mirrors the columns generated by data/generate_data.py."""
    amount: float
    timestamp: str
    transaction_type: str                   # UPI / IMPS / NEFT / RTGS
    sender_account_age_days: Optional[int] = 365
    receiver_account_age_days: Optional[int] = 365
    sender_tx_count_24h: Optional[int] = 0
    receiver_unique_senders_24h: Optional[int] = 0
    device_changed: Optional[bool] = False
    location_changed: Optional[bool] = False
    failed_login_attempts: Optional[int] = 0


class LegacyScoreRequest(BaseModel):
    """Legacy 10-float vector — kept for backward compat."""
    features: List[float]


class RichScoreResponse(BaseModel):
    risk_score: float
    risk_label: str
    recommendation: str
    reason: str


@router.post("/score", response_model=Union[RichScoreResponse, dict], dependencies=[Depends(verify_api_key)])
def score_transaction(payload: Union[RichScoreRequest, LegacyScoreRequest]):
    """
    Scores a transaction for fraud risk using the current global federated model.

    - RichScoreRequest  — preferred; uses the same core/preprocessing.transaction_to_features()
                          function used during training, ensuring feature alignment.
    - LegacyScoreRequest — accepts a raw 10-float vector for backward compatibility.
    """
    from api.main import trainer

    if isinstance(payload, LegacyScoreRequest):
        if len(payload.features) != 10:
            raise HTTPException(
                status_code=400,
                detail="Legacy features vector must contain exactly 10 floats.",
            )
        return trainer.predict(payload.features)

    # Rich path: delegate entirely to trainer.predict_rich which uses
    # core/preprocessing.transaction_to_features() — no separate mapping here.
    tx_dict = payload.dict()
    return trainer.predict_rich(tx_dict)
